spring:
  application:
    name: saga-orchestrator-service
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

server:
  port: 8082

logging:
  level:
    org:
      apache:
        kafka: OFF